=== lyontechhub/lyontechhub.github.io/schema/community.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "image": { "type": "string" },
    "name": { "type": "string" },
    "shortDescription": { "type": "string" },
    "tags": {
      "type": "array",
      "items": { "type": "string" },
      "uniqueItems": true
    },
    "patternsGoogleCalendar": {
      "type": "array",
      "items": { "type": "string" },
      "minItems": 1,
      "uniqueItems": true
    },
    "socialLinks": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "icon": { "type": "string" },
          "name": { "type": "string" },
          "url": { "type": "string" }
        },
        "required": [
          "url"
        ]
      },
      "uniqueItems": true
    },
    "slackChannels": {
      "type": "array",
      "items": { "type": "string" },
      "uniqueItems": true
    },
    "calendars": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "prefixTag": { "type": "string" },
          "url": { "type": "string" }
        },
        "required": [
          "url"
        ]
      },
      "uniqueItems": true
    }
  },
  "required": [
    "image",
    "name",
    "shortDescription",
    "tags",
    "socialLinks"
  ]
}

=== lyontechhub/lyontechhub.github.io/data/MakersLyon.json
{
  "image": "MakersLyon.png",
  "name": "MakersLyon",
  "shortDescription": "Les Apéros makers ont lieu tous les deux mois et visent à faire se rencontrer toute la communauté autour du faire, de la bidouille, les makers, etc. Le format est très informel, et vous pouvez venir présenter vos propres projets.",
  "patternsGoogleCalendar": [
    "MakersLyon"
  ],
  "tags": [
    "bidouille",
    "maker",
    "hack",
	"materiel",
	"impression3d"
  ],
  "socialLinks": [
    {
	  "name": "Discord",
      "url": "https://discord.gg/8cNzPerQx"
    }
  ]
}

=== lyontechhub/lyontechhub.github.io/data/LyonGameDev.json
{
  "image": "lyongamedev.png",
  "name": "LyonGameDev",
  "shortDescription": "Les brasseurs du jeu-vidéo lyonnais. Bières, pitchs et gros pixels... Pour l'instant c'est avant tout une rencontre mensuelle, mais cela peut devenir bien plus encore !",
  "tags": [
    "GameDev",
    "Jeu vidéo",
    "Game",
    "Video Game"
  ],
  "socialLinks": [
    {
      "icon": "link",
      "tooltip": "Web site",
      "url": "http://lyongamedev.pro"
    },
    {
      "icon": "twitter",
      "tooltip": "Twitter",
      "url": "https://twitter.com/lyon_dev"
    },
    {
      "icon": "linkedin",
      "tooltip": "Linked In",
      "url": "https://www.linkedin.com/company/lyongamedev/?viewAsMember=true"
    },
    {
      "icon": "facebook",
      "tooltip": "Facebook",
      "url": "https://www.facebook.com/LyonGameDevPage/"
    },
    {
      "icon": "github",
      "tooltip": "Git Hub Organization",
      "url": "https://github.com/lyongamedev"
    }
  ]
}

=== lyontechhub/lyontechhub.github.io/data/TupperVim.json
{
  "image": "TupperVim.svg",
  "name": "TupperVim",
  "shortDescription": "Les TupperVim sont des évènements où l’on partage des connaissances et des astuces à propos de Vim. Les TupperVim s’inspirent autant des agapes maçonniques du troisième millénaire que des soirées tupperware™ des années 60. Tout un concept.",
  "tags": [
    "vim",
    "Neovim",
    "TupperVim",
    "TupperLibre",
    "OpenSource",
    "Developpement",
    "Code",
    "terminal"
  ],
  "socialLinks": [
    {
      "url": "https://tuppervim.org/"
    },
    {
      "url": "https://discord.gg/rRuq3GwqfZ"
    },
    {
      "name": "Canal IRC",
      "url": "irc://irc.libera.chat/vim-fr"
    },
    {
      "name": "Liste de diffusion",
      "url": "https://framalistes.org/sympa/info/tuppervim"
    },
    {
      "url": "https://www.meetup.com/fr-FR/TupperLibre/"
    }
  ],
  "calendars": [
    { "url": "https://www.agendadulibre.org/events.ics?tag=vim&city=Lyon" }
  ]
}

=== lyontechhub/lyontechhub.github.io/data/LaboratoireOuvertLyonnais.json
{
  "image": "LaboratoireOuvertLyonnais.svg",
  "name": "Laboratoire Ouvert Lyonnais",
  "shortDescription": "Le Laboratoire Ouvert Lyonnais est un hackerspace proposant un espace pour sa communauté afin de réaliser et accompagner des projets, apprendre et partager des connaissances ou des technologies (peu importe le domaine), le tous dans la joie et la bonne humeur",
  "tags": [
    "Open source",
    "Électronique",
    "Informatique",
    "Hacking",
    "Ethical Hacker",
    "DIY",
    "Projets",
    "Hackerspace",
    "Bidouilles",
    "Apprendre",
    "Échange",
    "Partage",
    "Rencontre"
  ],
  "patternsGoogleCalendar": [
    "LaboratoireOuvertLyonnais"
  ],
  "socialLinks": [
    {
      "icon": "link",
      "tooltip": "Web site",
      "url": "https://labolyon.fr"
    },
    {
      "icon": "meetup",
      "tooltip": "Groupe Meetup",
      "url": "http://www.meetup.com/fr/Laboratoire-Ouvert-Lyonnais/"
    },
    {
      "icon": "code-fork",
      "tooltip": "Git Forge",
      "url": "https://git.labolyon.fr/"
    },
    {
      "icon": "weixin",
      "tooltip": "IRC",
      "url": "irc://irc.geeknode.org/labolyon"
    },
    {
      "icon": "twitter",
      "tooltip": "Twitter",
      "url": "https://twitter.com/LaboLyon"
    }
  ]
}

=== lyontechhub/lyontechhub.github.io/data/LyonCafeViePrivee.json
{
  "image": "LyonCafeViePrivee.png",
  "name": "Lyon Café Vie Privée",
  "shortDescription": "Collectif qui anime des ateliers et d'autres événements pour aider tout un chacun à reprendre le contrôle de sa vie privée sur Internet",
  "tags": [
    "Libre",
    "Opensource",
    "Vie privée",
    "flash-parties",
    "smartphones"
  ],
  "patternsGoogleCalendar": [
    "LCVP"
  ],
  "socialLinks": [
    {
      "name": "Site web",
      "url": "https://lyon-cvp.fr"
    },
    {
      "name": "Mastodon",
      "url": "https://mamot.fr/@lyonchiffrofete"
    },
    {
      "name": "Bluesky",
      "url": "https://bsky.app/profile/lyonchiffrofete.mamot.fr.ap.brid.gy"
    }
  ],
  "calendars": [
    { "url": "https://sync.infomaniak.com/calendars/BM04396/a473af33-7790-4622-9d34-b663e9ce2e3d?export" }
  ]
}

=== lyontechhub/lyontechhub.github.io/data/theDesignSociety.json
{
  "image": "theDesignSociety.png",
  "name": "The Design Society",
  "shortDescription": "Une société secrète si mal gardée qu’on est même sur les réseaux. On s’y retrouve entre pro et passionnés du Design dans différents formats : talks, apéros, et bien plus !",
  "tags": [
    "Design",
    "UX/UI Design",
    "Product Design",
    "User Research",
    "Design System",
    "DesignOps",
    "DA",
    "Motion Design"
  ],
  "patternsGoogleCalendar": [
    "TheDesignSociety"
  ],
  "socialLinks": [
    {
      "url": "https://www.thedesignsociety.fr/"
    },
    {
      "url": "https://www.eventbrite.fr/o/the-design-society-110792418841"
    },
    {
      "url": "https://www.linkedin.com/company/the-design-society-lyon/"
    },
    {
      "url": "https://www.instagram.com/thedesignsociety_lyon/"
    }
  ],
  "slackChannels": [
    "#thedesignsociety"
  ]
}
